apiVersion: autoscaler.mongodb.io/v1alpha1
kind: MongodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaler.mongodb.io/v1alpha1","kind":"MongodAutoscaler","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mongodboperator"},"name":"mongodautoscaler-sample","namespace":"mambo-mongod-cpu"},"spec":{"bitnami":{"namespace":"mambo-mongod-cpu","releaseName":"my-mongodb-sharded","servicePort":27017},"policy":{"cooldownSeconds":3600,"cpuTargetPercent":50,"cpuTolerancePercent":5,"iowaitTargetPercent":30,"iowaitTolerancePercent":5,"window":"5m","writeHeavyTargetPercent":70},"prometheus":{"nodeExporterPort":9100,"url":"http://prometheus-operated.monitoring.svc.cluster.local:9090"},"replicaScaleBounds":{"maxReplicas":1,"minReplicas":1},"shardScaleBounds":{"maxShards":2,"minShards":1}}}
  creationTimestamp: "2026-09-02T05:04:26Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodboperator
  name: mongodautoscaler-sample
  namespace: mambo-mongod-cpu
  resourceVersion: "11874421"
  uid: 81bf5c6e-261e-40a6-a1c6-f0a4f7d57603
spec:
  bitnami:
    namespace: mambo-mongod-cpu
    releaseName: my-mongodb-sharded
    servicePort: 27017
  policy:
    cooldownSeconds: 3600
    cpuTargetPercent: 50
    cpuTolerancePercent: 5
    iowaitTargetPercent: 30
    iowaitTolerancePercent: 5
    window: 5m
    writeHeavyTargetPercent: 70
  prometheus:
    nodeExporterPort: 9100
    url: http://prometheus-operated.monitoring.svc.cluster.local:9090
  replicaScaleBounds:
    maxReplicas: 1
    minReplicas: 1
  shardScaleBounds:
    maxShards: 2
    minShards: 1
status:
  lastDesiredReplicas: 1
  lastDesiredShards: 2
  lastObservedCPU: "55.306744"
  lastObservedIOWait: "2.067040"
  lastObservedWriteRatio: "0.000000"
  lastScaleTime: "2026-09-02T05:11:41Z"
  scalingPhase: Idle
  targetShardIndex: -1
