apiVersion: autoscaler.mongodb.io/v1alpha1
kind: MongodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: mongodboperator
    app.kubernetes.io/managed-by: kustomize
  name: mongodautoscaler-sample
  namespace: mambo-mongod-cpu
spec:
  # TODO(user): Add fields here
  bitnami:
    releaseName: my-mongodb-sharded
    namespace: mambo-mongod-cpu
    servicePort: 27017

  shardScaleBounds:
    minShards: 1
    maxShards: 2

  replicaScaleBounds:
    minReplicas: 1
    maxReplicas: 2

  policy:
    cpuTargetPercent: 60
    cpuTolerancePercent: 10
    iowaitTargetPercent: 30
    iowaitTolerancePercent: 5
    writeHeavyTargetPercent: 70
    window: 5m
    cooldownSeconds: 300

  prometheus:
    url: http://prometheus-operated.monitoring.svc.cluster.local:9090
    nodeExporterPort: 9100